# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  desc "Setup keychain & certificates lane"
  lane :setup_certificates_lane do
    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      password: ENV["LARGE_SECRET_PASSPHRASE"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
    import_certificate(
      certificate_path: "fastlane/ios_distribution.p12",
      certificate_password: ENV["LARGE_SECRET_PASSPHRASE"],
      keychain_name: ENV["KEYCHAIN_NAME"],
      keychain_password: ENV["LARGE_SECRET_PASSPHRASE"]
    )
    import_certificate(
      certificate_path: "fastlane/AppleWWDRCAG3.cer",
      keychain_name: ENV["KEYCHAIN_NAME"],
      keychain_password: ENV["LARGE_SECRET_PASSPHRASE"]
    )
    install_provisioning_profile(path: "fastlane/NoteDelight_Distribution_Profile.mobileprovision")
  end
  desc "AppStore build lane with gym"
  lane :appstore_build_gym_lane do
#     increment_version_number # Automatically increment version number. Manually: "bundle exec fastlane run increment_version_number".
    build_num = app_store_build_number(api_key_path:"fastlane/28F5CB4337.json", live: false)
    increment_build_number(
      build_number: build_num + 1 # set a specific number
    )
    gym(
      scheme: 'iosApp',
      export_method: 'app-store',
      export_options: {
        provisioningProfiles: {
          "com.softartdev.notedelight" => "NoteDelight: Distribution Profile"
        }
      }
    )
  end
  desc "AppStore publish lane with deliver"
  lane :appstore_publish_deliver_lane do
    deliver(
      api_key_path: "fastlane/28F5CB4337.json",
      submit_for_review: true,
      automatic_release: true, # Automatically released once it's approved
      force: true, # Skip verification of HTML preview
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      submission_information: { add_id_info_uses_idfa: false }
    )
  end
end
