# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  desc "Test lane with scan"
  lane :test_scan_lane do
    scan(scheme: 'iosApp', suppress_xcode_output: false)
  end
  desc "Build lane with gym"
  lane :build_gym_lane do
    gym(scheme: 'iosApp')
  end
end
