target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'ios_compose_kit', :path => '../ios-compose-kit'
end

target 'oldApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared/'
end