package com.softartdev.notedelight.ui.dialog.security

import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import notedelight.ui.shared.generated.resources.Res
import notedelight.ui.shared.generated.resources.save
import org.jetbrains.compose.resources.stringResource

/**
 * Test tags for [EnterPasswordDialog]
 */
const val ENTER_PASSWORD_DIALOG_TAG = "ENTER_PASSWORD_DIALOG_TAG"

const val ENTER_PASSWORD_DIALOG_LABEL_TAG = "ENTER_PASSWORD_DIALOG_LABEL_TAG"
const val ENTER_PASSWORD_DIALOG_VISIBILITY_TAG = "ENTER_PASSWORD_DIALOG_VISIBILITY_TAG"
const val ENTER_PASSWORD_DIALOG_FIELD_TAG = "ENTER_PASSWORD_DIALOG_FIELD_TAG"

const val ENTER_PASSWORD_DIALOG_SAVE_BUTTON_TAG = "ENTER_PASSWORD_DIALOG_SAVE_BUTTON_TAG"

/**
 * Test tags for [ConfirmPasswordDialog]
 */
const val CONFIRM_PASSWORD_DIALOG_TAG = "CONFIRM_PASSWORD_DIALOG_TAG"

const val CONFIRM_PASSWORD_DIALOG_LABEL_TAG = "CONFIRM_PASSWORD_DIALOG_LABEL_TAG"
const val CONFIRM_PASSWORD_DIALOG_VISIBILITY_TAG = "CONFIRM_PASSWORD_DIALOG_VISIBILITY_TAG"
const val CONFIRM_PASSWORD_DIALOG_FIELD_TAG = "CONFIRM_PASSWORD_DIALOG_FIELD_TAG"

const val CONFIRM_PASSWORD_DIALOG_REPEAT_LABEL_TAG = "CONFIRM_PASSWORD_DIALOG_REPEAT_LABEL_TAG"
const val CONFIRM_PASSWORD_DIALOG_REPEAT_VISIBILITY_TAG = "CONFIRM_PASSWORD_DIALOG_REPEAT_VISIBILITY_TAG"
const val CONFIRM_PASSWORD_DIALOG_REPEAT_FIELD_TAG = "CONFIRM_PASSWORD_DIALOG_REPEAT_FIELD_TAG"

const val CONFIRM_PASSWORD_DIALOG_SAVE_BUTTON_TAG = "CONFIRM_PASSWORD_DIALOG_SAVE_BUTTON_TAG"

/**
 * Test tags for [ChangePasswordDialog]
 */
const val CHANGE_PASSWORD_DIALOG_TAG = "CHANGE_PASSWORD_DIALOG_TAG"

const val CHANGE_PASSWORD_DIALOG_OLD_LABEL_TAG = "CHANGE_PASSWORD_DIALOG_OLD_LABEL_TAG"
const val CHANGE_PASSWORD_DIALOG_OLD_VISIBILITY_TAG = "CHANGE_PASSWORD_DIALOG_OLD_VISIBILITY_TAG"
const val CHANGE_PASSWORD_DIALOG_OLD_FIELD_TAG = "CHANGE_PASSWORD_DIALOG_OLD_FIELD_TAG"

const val CHANGE_PASSWORD_DIALOG_NEW_LABEL_TAG = "CHANGE_PASSWORD_DIALOG_NEW_LABEL_TAG"
const val CHANGE_PASSWORD_DIALOG_NEW_VISIBILITY_TAG = "CHANGE_PASSWORD_DIALOG_NEW_VISIBILITY_TAG"
const val CHANGE_PASSWORD_DIALOG_NEW_FIELD_TAG = "CHANGE_PASSWORD_DIALOG_NEW_FIELD_TAG"

const val CHANGE_PASSWORD_DIALOG_REPEAT_LABEL_TAG = "CHANGE_PASSWORD_DIALOG_REPEAT_LABEL_TAG"
const val CHANGE_PASSWORD_DIALOG_REPEAT_VISIBILITY_TAG = "CHANGE_PASSWORD_DIALOG_REPEAT_VISIBILITY_TAG"
const val CHANGE_PASSWORD_DIALOG_REPEAT_FIELD_TAG = "CHANGE_PASSWORD_DIALOG_REPEAT_FIELD_TAG"

const val CHANGE_PASSWORD_DIALOG_SAVE_BUTTON_TAG = "CHANGE_PASSWORD_DIALOG_SAVE_BUTTON_TAG"

/**
 * A common save button for password dialogs.
 */
@Composable
fun PasswordSaveButton(
    modifier: Modifier = Modifier,
    tag: String,
    onClick: () -> Unit,
) = Button(
    modifier = modifier.testTag(tag),
    onClick = onClick
) { Text(stringResource(Res.string.save)) }
