package com.softartdev.notedelight.util

/**
 * Test tags for [com.softartdev.notedelight.ui.signin.SignInScreen]
 */
const val SIGN_IN_PASSWORD_LABEL_TAG = "SIGN_IN_PASSWORD_FIELD_LABEL_TAG"
const val SIGN_IN_PASSWORD_VISIBILITY_TAG = "SIGN_IN_PASSWORD_FIELD_VISIBILITY_TAG"
const val SIGN_IN_PASSWORD_FIELD_TAG = "SIGN_IN_PASSWORD_FIELD_TAG"
const val SIGN_IN_SETTINGS_BUTTON_TAG = "SIGN_IN_SETTINGS_BUTTON_TAG"
const val SIGN_IN_BUTTON_TAG = "SIGN_IN_BUTTON_TAG"

/**
 * Test tags for [com.softartdev.notedelight.ui.dialog.security.EnterPasswordDialog]
 */
const val ENTER_PASSWORD_DIALOG_TAG = "ENTER_PASSWORD_DIALOG_TAG"

const val ENTER_PASSWORD_DIALOG_LABEL_TAG = "ENTER_PASSWORD_DIALOG_LABEL_TAG"
const val ENTER_PASSWORD_DIALOG_VISIBILITY_TAG = "ENTER_PASSWORD_DIALOG_VISIBILITY_TAG"
const val ENTER_PASSWORD_DIALOG_FIELD_TAG = "ENTER_PASSWORD_DIALOG_FIELD_TAG"

const val ENTER_PASSWORD_DIALOG_SAVE_BUTTON_TAG = "ENTER_PASSWORD_DIALOG_SAVE_BUTTON_TAG"

/**
 * Test tags for [com.softartdev.notedelight.ui.dialog.security.ConfirmPasswordDialog]
 */
const val CONFIRM_PASSWORD_DIALOG_TAG = "CONFIRM_PASSWORD_DIALOG_TAG"

const val CONFIRM_PASSWORD_DIALOG_LABEL_TAG = "CONFIRM_PASSWORD_DIALOG_LABEL_TAG"
const val CONFIRM_PASSWORD_DIALOG_VISIBILITY_TAG = "CONFIRM_PASSWORD_DIALOG_VISIBILITY_TAG"
const val CONFIRM_PASSWORD_DIALOG_FIELD_TAG = "CONFIRM_PASSWORD_DIALOG_FIELD_TAG"

const val CONFIRM_PASSWORD_DIALOG_REPEAT_LABEL_TAG = "CONFIRM_PASSWORD_DIALOG_REPEAT_LABEL_TAG"
const val CONFIRM_PASSWORD_DIALOG_REPEAT_VISIBILITY_TAG = "CONFIRM_PASSWORD_DIALOG_REPEAT_VISIBILITY_TAG"
const val CONFIRM_PASSWORD_DIALOG_REPEAT_FIELD_TAG = "CONFIRM_PASSWORD_DIALOG_REPEAT_FIELD_TAG"

const val CONFIRM_PASSWORD_DIALOG_SAVE_BUTTON_TAG = "CONFIRM_PASSWORD_DIALOG_SAVE_BUTTON_TAG"

/**
 * Test tags for [com.softartdev.notedelight.ui.dialog.security.ChangePasswordDialog]
 */
const val CHANGE_PASSWORD_DIALOG_TAG = "CHANGE_PASSWORD_DIALOG_TAG"

const val CHANGE_PASSWORD_DIALOG_OLD_LABEL_TAG = "CHANGE_PASSWORD_DIALOG_OLD_LABEL_TAG"
const val CHANGE_PASSWORD_DIALOG_OLD_VISIBILITY_TAG = "CHANGE_PASSWORD_DIALOG_OLD_VISIBILITY_TAG"
const val CHANGE_PASSWORD_DIALOG_OLD_FIELD_TAG = "CHANGE_PASSWORD_DIALOG_OLD_FIELD_TAG"

const val CHANGE_PASSWORD_DIALOG_NEW_LABEL_TAG = "CHANGE_PASSWORD_DIALOG_NEW_LABEL_TAG"
const val CHANGE_PASSWORD_DIALOG_NEW_VISIBILITY_TAG = "CHANGE_PASSWORD_DIALOG_NEW_VISIBILITY_TAG"
const val CHANGE_PASSWORD_DIALOG_NEW_FIELD_TAG = "CHANGE_PASSWORD_DIALOG_NEW_FIELD_TAG"

const val CHANGE_PASSWORD_DIALOG_REPEAT_LABEL_TAG = "CHANGE_PASSWORD_DIALOG_REPEAT_LABEL_TAG"
const val CHANGE_PASSWORD_DIALOG_REPEAT_VISIBILITY_TAG = "CHANGE_PASSWORD_DIALOG_REPEAT_VISIBILITY_TAG"
const val CHANGE_PASSWORD_DIALOG_REPEAT_FIELD_TAG = "CHANGE_PASSWORD_DIALOG_REPEAT_FIELD_TAG"

const val CHANGE_PASSWORD_DIALOG_SAVE_BUTTON_TAG = "CHANGE_PASSWORD_DIALOG_SAVE_BUTTON_TAG"

/**
 * Test tags for [com.softartdev.notedelight.ui.main.MainScreen]
 */
const val MAIN_SETTINGS_BUTTON_TAG = "MAIN_SETTINGS_BUTTON_TAG"
const val CREATE_NOTE_FAB_TAG = "CREATE_NOTE_FAB_TAG"
const val EMPTY_RESULT_LABEL_TAG = "EMPTY_RESULT_LABEL_TAG"

/**
 * Test tags for [com.softartdev.notedelight.ui.main.NoteDetail]
 */
const val SAVE_NOTE_BUTTON_TAG = "SAVE_NOTE_BUTTON_TAG"
const val EDIT_TITLE_BUTTON_TAG = "EDIT_TITLE_BUTTON_TAG"
const val DELETE_NOTE_BUTTON_TAG = "DELETE_NOTE_BUTTON_TAG"

/**
 * Test tags for [com.softartdev.notedelight.ui.settings.master.SettingsMasterScreen]
 */
const val SETTINGS_CATEGORY_THEME_TAG = "SETTINGS_CATEGORY_THEME_TAG"
const val SETTINGS_CATEGORY_SECURITY_TAG = "SETTINGS_CATEGORY_SECURITY_TAG"
const val SETTINGS_CATEGORY_BACKUP_TAG = "SETTINGS_CATEGORY_BACKUP_TAG"
const val SETTINGS_CATEGORY_INFO_TAG = "SETTINGS_CATEGORY_INFO_TAG"
const val ENABLE_ENCRYPTION_SWITCH_TAG = "ENABLE_ENCRYPTION_SWITCH_TAG"
const val SET_PASSWORD_BUTTON_TAG = "SET_PASSWORD_BUTTON_TAG"
const val LANGUAGE_BUTTON_TAG = "LANGUAGE_BUTTON_TAG"
const val EXPORT_DATABASE_BUTTON_TAG = "EXPORT_DATABASE_BUTTON_TAG"
const val IMPORT_DATABASE_BUTTON_TAG = "IMPORT_DATABASE_BUTTON_TAG"

/**
 * Test tags for [com.softartdev.notedelight.ui.dialog.LanguageDialog]
 */
const val CHOOSE_LANGUAGE_DIALOG_TITLE_TAG = "CHOOSE_LANGUAGE_DIALOG_TITLE_TAG"
const val OK_BUTTON_TAG = "OK_BUTTON_TAG"

/**
 * Test tags for [com.softartdev.notedelight.ui.dialog.EditTitleDialog]
 */
const val ENTER_TITLE_DIALOG_TAG = "ENTER_TITLE_DIALOG_TAG"

/**
 * Test tags for [com.softartdev.notedelight.ui.dialog.note.SaveDialog]
 */
const val SAVE_NOTE_DIALOG_TAG = "SAVE_NOTE_DIALOG_TAG"

/**
 * Test tags for dialog buttons
 */
const val YES_BUTTON_TAG = "YES_BUTTON_TAG"
const val NO_BUTTON_TAG = "NO_BUTTON_TAG"
const val CANCEL_BUTTON_TAG = "CANCEL_BUTTON_TAG"
