# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store # Uploads the APK built in the gradle step above
  end

  lane :playstore do
    gradle(
      task: 'clean bundle',
      build_type: 'Release'
    )
    upload_to_play_store # Uploads the AAB built in the gradle step above
  end

  lane :clean_test_bundle_publish do
    gradle(
      task: 'clean test bundle',
      build_type: 'Release'
    )
    upload_to_play_store # Uploads the AAB built in the gradle step above
  end

  lane :build_bundle_publish do
    gradle(
      task: 'build bundle', # Task 'build' include 'assemble', 'lint' & 'test'
      build_type: 'Release'
    )
    upload_to_play_store skip_upload_apk:true
  end
end
